FROM node:16
WORKDIR /app
RUN addgroup app && adduser -S -G app app && chown -R app /app
USER app
RUN ls -1

COPY package*.json ./
RUN node --version
RUN npm cache clean --force
RUN npm update
RUN npm ci
COPY . ./
EXPOSE 5000
ARG PORT
ENV PORT=${PORT}
ARG MONGODB_URL
ENV MONGODB_URL=${MONGODB_URL}
ARG PASSWORD_SECRET_KEY
ENV PASSWORD_SECRET_KEY=${PASSWORD_SECRET_KEY}
ARG TOKEN_SECRET_KEY
ENV TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
ARG VERIFICATION_SECRET_KEY
ENV VERIFICATION_SECRET_KEY=${VERIFICATION_SECRET_KEY}
ARG EMAIL_USERNAME
ENV EMAIL_USERNAME=${EMAIL_USERNAME}
ARG EMAIL_PASSWORD
ENV EMAIL_PASSWORD=${EMAIL_PASSWORD}
CMD ["npm", "run", "start"]

